name: 'dbt_spotify'
version: '2.0.2'

profile: 'dbt_spotify'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_spotify:
    staging:
      +materialized: view
      +docs:
        node_color: 'silver'
    marts:
      +materialized: table
      +docs:
        node_color: salmon
      reports:
        +docs:
          node_color: skyblue
